openapi: 3.0.3
servers:
  - url: /v3
info:
  description: File for testing json roundtripping of oneOf defns in scala 2.x with jsoniter-scala
  version: 1.0.20-SNAPSHOT
  title: OneOf Json test for jsoniter-scala
tags: [ ]
paths:
  '/adt/test':
    post:
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ADTWithDiscriminator'
      requestBody:
        required: true
        description: Update an existent user in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ADTWithDiscriminatorNoMapping'
    put:
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ADTWithoutDiscriminator'
      requestBody:
        required: true
        description: Update an existent user in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ADTWithoutDiscriminator'
  '/xml/endpoint':
    post:
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        "200":
          description: An object
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Pet'
  '/recursive/schema/endpoint':
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Node'
      responses:
        "200":
          description: An object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'

components:
  schemas:
    ADTWithDiscriminator:
      type: object
      oneOf:
        - $ref: '#/components/schemas/SubtypeWithD1'
        - $ref: '#/components/schemas/SubtypeWithD2'
      discriminator:
        propertyName: type
        mapping:
          'SubA': '#/components/schemas/SubtypeWithD1'
          'SubB': '#/components/schemas/SubtypeWithD2'
    # This has the same members as ADTWithDiscriminator, to test that we can extend multiple sealed traits in our ADT mappings
    ADTWithDiscriminatorNoMapping:
      type: object
      oneOf:
        - $ref: '#/components/schemas/SubtypeWithD1'
        - $ref: '#/components/schemas/SubtypeWithD2'
      discriminator:
        propertyName: type
    SubtypeWithD1:
      type: object
      required:
        - s
      properties:
        s:
          type: string
        i:
          type: integer
        d:
          type: number
          format: double
    SubtypeWithD2:
      type: object
      required:
        - s
      properties:
        s:
          type: string
        a:
          type: array
          items:
            type: string
    ADTWithoutDiscriminator:
      type: object
      oneOf:
        ## A 'SubtypeWithoutD1' with only 'a' and 'd' fields set could be decoded as either a SubtypeWithoutD2 or SubtypeWithoutD3,
        ## and so must be defined first here, or else we'd fail validation
        - $ref: '#/components/schemas/SubtypeWithoutD1'
        - $ref: '#/components/schemas/SubtypeWithoutD2'
        - $ref: '#/components/schemas/SubtypeWithoutD3'
    SubtypeWithoutD1:
      type: object
      required:
        - s
        - a
      properties:
        s:
          type: string
        i:
          type: integer
        a:
          type: array
          items:
            type: string
        absent:
          type: string
    SubtypeWithoutD2:
      type: object
      required:
        - a
      properties:
        a:
          type: array
          items:
            type: string
        absent:
          type: string
    SubtypeWithoutD3:
      type: object
      required:
        - s
      properties:
        s:
          type: string
        i:
          type: integer
        e:
          $ref: '#/components/schemas/AnEnum'
        absent:
          type: string
    AnEnum:
      type: string
      enum:
        - Foo
        - Bar
        - Baz
    Pet:
      x-swagger-router-model: io.swagger.petstore.model.Pet
      required:
        - name
        - photoUrls
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: doggie
        category:
          $ref: '#/components/schemas/Category'
        photoUrls:
          type: array
          xml:
            wrapped: true
          items:
            type: string
            xml:
              name: photoUrl
        tags:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
            xml:
              name: tag
        tags2:
          type: array
          xml:
            wrapped: false
            name: extra-tags
          items:
            $ref: '#/components/schemas/Tag2'
        status:
          $ref: '#/components/schemas/PetStatus'
      xml:
        name: pet
      type: object
    PetStatus:
      type: string
      description: pet status in the store
      enum:
        - available
        - pending
        - sold
    Tag:
      x-swagger-router-model: io.swagger.petstore.model.Tag
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: tag
      type: object
    Tag2:
      x-swagger-router-model: io.swagger.petstore.model.Tag2
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: tag
      type: object
    Category:
      x-swagger-router-model: io.swagger.petstore.model.Category
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Dogs
      xml:
        name: category
      type: object
    Node:
      title: Node
      type: object
      required:
        - value
      properties:
        value:
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/Node'
