openapi: 3.0.0
info:
  title: separate files for models test
  version: 1.0.0
paths:
  /books:
    get:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Animal'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Books'
components:
  schemas:
    Book:
      type: object
      required: [ title ]
      properties:
        title:
          type: string
    Books:
      type: array
      items:
        $ref: '#/components/schemas/Book'
    Animal:
      required:
        - type
      properties:
        type:
          type: string
      oneOf:
        - $ref: '#/components/schemas/Badger'
        - $ref: '#/components/schemas/Ferret'
    Badger:
      title: Badger
      type: object
      required:
        - snuffles
        - type
      properties:
        snuffles:
          type: boolean
        typeOfSnuffle:
          type: string
          enum:
            - Hungry
            - Noisy
        type:
          type: string
    Ferret:
      title: Badger
      type: object
      required:
        - smells
        - type
      properties:
        smells:
          type: boolean
        type:
          type: string
