version: 1
labels:
  - label: "automerge"
    authors: ["softwaremill-ci"]
    files:
      - "build.sbt"
      - "project/Versions.scala"
      - "project/plugins.sbt"
      - "examples/src/main/scala/.*"
  - label: "dependency"
    authors: ["softwaremill-ci"]
    files:
      - "build.sbt"
      - "project/Versions.scala"
      - "project/plugins.sbt"
      - "examples/src/main\scala/.*"
