pull_request_rules:
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
  - name: automatic merge for github-actions pull requests affecting build.sbt
    conditions:
      - author=github-actions
      - check-success=ci (JVM)
      - check-success=ci (JS)
      - check-success=mima
      - "#files=1"
      - files=build.sbt
    actions:
      merge:
        method: merge
  - name: automatic merge for github-actions pull requests affecting project plugins.sbt
    conditions:
      - author=github-actions
      - check-success=ci (JVM)
      - check-success=ci (JS)
      - check-success=mima
      - "#files=1"
      - files=project/plugins.sbt
    actions:
      merge:
        method: merge
  - name: semi-automatic merge for github-actions pull requests
    conditions:
      - author=github-actions
      - check-success=ci (JVM)
      - check-success=ci (JS)
      - check-success=mima
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: automatic merge for github-actions pull requests affecting project build.properties
    conditions:
      - author=github-actions
      - check-success=ci (JVM)
      - check-success=ci (JS)
      - check-success=mima
      - "#files=1"
      - files=project/build.properties
    actions:
      merge:
        method: merge
  - name: automatic merge for github-actions pull requests affecting .scalafmt.conf
    conditions:
      - author=github-actions
      - check-success=ci (JVM)
      - check-success=ci (JS)
      - check-success=mima
      - "#files=1"
      - files=.scalafmt.conf
    actions:
      merge:
        method: merge
  - name: automatic merge for github-actions pull requests affecting project Versions.scala
    conditions:
      - author=github-actions
      - check-success=ci (JVM)
      - check-success=ci (JS)
      - check-success=mima
      - "#files=1"
      - files=project/Versions.scala
    actions:
      merge:
        method: merge
  - name: add label to github-actions PRs
    conditions:
      - author=github-actions
    actions:
      label:
        add:
          - dependency