// auto-generated by sbt-boilerplate
package sttp.tapir.internal

object ProductToParams {
  def apply(p: Product, arity: Int): Any = {
    arity match {
      case 0 => ()
      case 1 => p.productElement(0)
      case 2 => (p.productElement(0), p.productElement(1))
      case 3 => (p.productElement(0), p.productElement(1), p.productElement(2))
      case 4 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3))
      case 5 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4))
      case 6 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5))
      case 7 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6))
      case 8 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7))
      case 9 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7), p.productElement(8))
      case 10 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7), p.productElement(8), p.productElement(9))
      case 11 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7), p.productElement(8), p.productElement(9), p.productElement(10))
      case 12 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7), p.productElement(8), p.productElement(9), p.productElement(10), p.productElement(11))
      case 13 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7), p.productElement(8), p.productElement(9), p.productElement(10), p.productElement(11), p.productElement(12))
      case 14 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7), p.productElement(8), p.productElement(9), p.productElement(10), p.productElement(11), p.productElement(12), p.productElement(13))
      case 15 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7), p.productElement(8), p.productElement(9), p.productElement(10), p.productElement(11), p.productElement(12), p.productElement(13), p.productElement(14))
      case 16 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7), p.productElement(8), p.productElement(9), p.productElement(10), p.productElement(11), p.productElement(12), p.productElement(13), p.productElement(14), p.productElement(15))
      case 17 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7), p.productElement(8), p.productElement(9), p.productElement(10), p.productElement(11), p.productElement(12), p.productElement(13), p.productElement(14), p.productElement(15), p.productElement(16))
      case 18 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7), p.productElement(8), p.productElement(9), p.productElement(10), p.productElement(11), p.productElement(12), p.productElement(13), p.productElement(14), p.productElement(15), p.productElement(16), p.productElement(17))
      case 19 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7), p.productElement(8), p.productElement(9), p.productElement(10), p.productElement(11), p.productElement(12), p.productElement(13), p.productElement(14), p.productElement(15), p.productElement(16), p.productElement(17), p.productElement(18))
      case 20 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7), p.productElement(8), p.productElement(9), p.productElement(10), p.productElement(11), p.productElement(12), p.productElement(13), p.productElement(14), p.productElement(15), p.productElement(16), p.productElement(17), p.productElement(18), p.productElement(19))
      case 21 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7), p.productElement(8), p.productElement(9), p.productElement(10), p.productElement(11), p.productElement(12), p.productElement(13), p.productElement(14), p.productElement(15), p.productElement(16), p.productElement(17), p.productElement(18), p.productElement(19), p.productElement(20))
      case 22 => (p.productElement(0), p.productElement(1), p.productElement(2), p.productElement(3), p.productElement(4), p.productElement(5), p.productElement(6), p.productElement(7), p.productElement(8), p.productElement(9), p.productElement(10), p.productElement(11), p.productElement(12), p.productElement(13), p.productElement(14), p.productElement(15), p.productElement(16), p.productElement(17), p.productElement(18), p.productElement(19), p.productElement(20), p.productElement(21))
    }
  }
}
