package sttp.tapir.json.pickler.next.internal.runtime

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import sttp.tapir.Schema
import sttp.tapir.json.pickler.next.Pickler

/** Factory for the final [[Pickler]] instance emitted by the derivation macro.
  *
  * The macro emits a call to [[instance]] rather than expanding a `new Pickler[A] { ... }` literal at each derivation
  * site: every anonymous class expansion would produce a separate `.class` file per derived type, whereas the one
  * below is defined once and shared by every derived pickler. (The `JsonValueCodec` itself is an anonymous class
  * generated by `JsonCodecMaker`, so that cost is paid once per type either way.)
  */
object PicklerFactories {

  def instance[A](schemaValue: Schema[A], codecValue: JsonValueCodec[A]): Pickler[A] = new Pickler[A] {
    val schema: Schema[A] = schemaValue
    val codec: JsonValueCodec[A] = codecValue
  }
}
