// auto-generated by sbt-boilerplate
package sttp.tapir.typelevel

trait ParamsToTuple[I] {
  type Out
  def toTuple(i: I): Out
}

object ParamsToTuple extends LowPriorityParamsToTuple {

  implicit def tuple2toTuple[A1, A2]: Aux[Tuple2[A1, A2], Tuple2[A1, A2]] = new ParamsToTuple[Tuple2[A1, A2]] {
    override type Out = Tuple2[A1, A2]
    override def toTuple(i: Tuple2[A1, A2]): Tuple2[A1, A2] = i
  }
  implicit def tuple3toTuple[A1, A2, A3]: Aux[Tuple3[A1, A2, A3], Tuple3[A1, A2, A3]] = new ParamsToTuple[Tuple3[A1, A2, A3]] {
    override type Out = Tuple3[A1, A2, A3]
    override def toTuple(i: Tuple3[A1, A2, A3]): Tuple3[A1, A2, A3] = i
  }
  implicit def tuple4toTuple[A1, A2, A3, A4]: Aux[Tuple4[A1, A2, A3, A4], Tuple4[A1, A2, A3, A4]] = new ParamsToTuple[Tuple4[A1, A2, A3, A4]] {
    override type Out = Tuple4[A1, A2, A3, A4]
    override def toTuple(i: Tuple4[A1, A2, A3, A4]): Tuple4[A1, A2, A3, A4] = i
  }
  implicit def tuple5toTuple[A1, A2, A3, A4, A5]: Aux[Tuple5[A1, A2, A3, A4, A5], Tuple5[A1, A2, A3, A4, A5]] = new ParamsToTuple[Tuple5[A1, A2, A3, A4, A5]] {
    override type Out = Tuple5[A1, A2, A3, A4, A5]
    override def toTuple(i: Tuple5[A1, A2, A3, A4, A5]): Tuple5[A1, A2, A3, A4, A5] = i
  }
  implicit def tuple6toTuple[A1, A2, A3, A4, A5, A6]: Aux[Tuple6[A1, A2, A3, A4, A5, A6], Tuple6[A1, A2, A3, A4, A5, A6]] = new ParamsToTuple[Tuple6[A1, A2, A3, A4, A5, A6]] {
    override type Out = Tuple6[A1, A2, A3, A4, A5, A6]
    override def toTuple(i: Tuple6[A1, A2, A3, A4, A5, A6]): Tuple6[A1, A2, A3, A4, A5, A6] = i
  }
  implicit def tuple7toTuple[A1, A2, A3, A4, A5, A6, A7]: Aux[Tuple7[A1, A2, A3, A4, A5, A6, A7], Tuple7[A1, A2, A3, A4, A5, A6, A7]] = new ParamsToTuple[Tuple7[A1, A2, A3, A4, A5, A6, A7]] {
    override type Out = Tuple7[A1, A2, A3, A4, A5, A6, A7]
    override def toTuple(i: Tuple7[A1, A2, A3, A4, A5, A6, A7]): Tuple7[A1, A2, A3, A4, A5, A6, A7] = i
  }
  implicit def tuple8toTuple[A1, A2, A3, A4, A5, A6, A7, A8]: Aux[Tuple8[A1, A2, A3, A4, A5, A6, A7, A8], Tuple8[A1, A2, A3, A4, A5, A6, A7, A8]] = new ParamsToTuple[Tuple8[A1, A2, A3, A4, A5, A6, A7, A8]] {
    override type Out = Tuple8[A1, A2, A3, A4, A5, A6, A7, A8]
    override def toTuple(i: Tuple8[A1, A2, A3, A4, A5, A6, A7, A8]): Tuple8[A1, A2, A3, A4, A5, A6, A7, A8] = i
  }
  implicit def tuple9toTuple[A1, A2, A3, A4, A5, A6, A7, A8, A9]: Aux[Tuple9[A1, A2, A3, A4, A5, A6, A7, A8, A9], Tuple9[A1, A2, A3, A4, A5, A6, A7, A8, A9]] = new ParamsToTuple[Tuple9[A1, A2, A3, A4, A5, A6, A7, A8, A9]] {
    override type Out = Tuple9[A1, A2, A3, A4, A5, A6, A7, A8, A9]
    override def toTuple(i: Tuple9[A1, A2, A3, A4, A5, A6, A7, A8, A9]): Tuple9[A1, A2, A3, A4, A5, A6, A7, A8, A9] = i
  }
  implicit def tuple10toTuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10]: Aux[Tuple10[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10], Tuple10[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10]] = new ParamsToTuple[Tuple10[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10]] {
    override type Out = Tuple10[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10]
    override def toTuple(i: Tuple10[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10]): Tuple10[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10] = i
  }
  implicit def tuple11toTuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11]: Aux[Tuple11[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11], Tuple11[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11]] = new ParamsToTuple[Tuple11[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11]] {
    override type Out = Tuple11[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11]
    override def toTuple(i: Tuple11[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11]): Tuple11[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11] = i
  }
  implicit def tuple12toTuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12]: Aux[Tuple12[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12], Tuple12[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12]] = new ParamsToTuple[Tuple12[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12]] {
    override type Out = Tuple12[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12]
    override def toTuple(i: Tuple12[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12]): Tuple12[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12] = i
  }
  implicit def tuple13toTuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13]: Aux[Tuple13[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13], Tuple13[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13]] = new ParamsToTuple[Tuple13[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13]] {
    override type Out = Tuple13[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13]
    override def toTuple(i: Tuple13[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13]): Tuple13[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13] = i
  }
  implicit def tuple14toTuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14]: Aux[Tuple14[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14], Tuple14[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14]] = new ParamsToTuple[Tuple14[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14]] {
    override type Out = Tuple14[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14]
    override def toTuple(i: Tuple14[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14]): Tuple14[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14] = i
  }
  implicit def tuple15toTuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15]: Aux[Tuple15[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15], Tuple15[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15]] = new ParamsToTuple[Tuple15[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15]] {
    override type Out = Tuple15[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15]
    override def toTuple(i: Tuple15[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15]): Tuple15[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15] = i
  }
  implicit def tuple16toTuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16]: Aux[Tuple16[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16], Tuple16[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16]] = new ParamsToTuple[Tuple16[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16]] {
    override type Out = Tuple16[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16]
    override def toTuple(i: Tuple16[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16]): Tuple16[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16] = i
  }
  implicit def tuple17toTuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17]: Aux[Tuple17[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17], Tuple17[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17]] = new ParamsToTuple[Tuple17[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17]] {
    override type Out = Tuple17[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17]
    override def toTuple(i: Tuple17[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17]): Tuple17[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17] = i
  }
  implicit def tuple18toTuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18]: Aux[Tuple18[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18], Tuple18[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18]] = new ParamsToTuple[Tuple18[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18]] {
    override type Out = Tuple18[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18]
    override def toTuple(i: Tuple18[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18]): Tuple18[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18] = i
  }
  implicit def tuple19toTuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19]: Aux[Tuple19[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19], Tuple19[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19]] = new ParamsToTuple[Tuple19[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19]] {
    override type Out = Tuple19[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19]
    override def toTuple(i: Tuple19[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19]): Tuple19[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19] = i
  }
  implicit def tuple20toTuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20]: Aux[Tuple20[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20], Tuple20[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20]] = new ParamsToTuple[Tuple20[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20]] {
    override type Out = Tuple20[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20]
    override def toTuple(i: Tuple20[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20]): Tuple20[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20] = i
  }
  implicit def tuple21toTuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21]: Aux[Tuple21[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21], Tuple21[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21]] = new ParamsToTuple[Tuple21[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21]] {
    override type Out = Tuple21[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21]
    override def toTuple(i: Tuple21[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21]): Tuple21[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21] = i
  }
  implicit def tuple22toTuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22]: Aux[Tuple22[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22], Tuple22[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22]] = new ParamsToTuple[Tuple22[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22]] {
    override type Out = Tuple22[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22]
    override def toTuple(i: Tuple22[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22]): Tuple22[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22] = i
  }
}

trait LowPriorityParamsToTuple {
  type Aux[I, T] = ParamsToTuple[I] { type Out = T }

  implicit def singleToTuple[A]: Aux[A, Tuple1[A]] = new ParamsToTuple[A] {
    override type Out = Tuple1[A]
    override def toTuple(i: A): Tuple1[A] = Tuple1(i)
  }
}
