// auto-generated by sbt-boilerplate
package sttp.tapir.typelevel

/** Implicits values of this type are defined for tuples of arity 2+, and split the tuple into the head type and tail type.
  * @tparam TUPLE
  *   The tuple type.
  * @tparam HEAD
  *   The type of the tuple head.
  * @tparam TAIL
  *   The type of the tuple with the head removed.
  */
trait TupleHeadAndTail[TUPLE, HEAD, TAIL]

object TupleHeadAndTail {
  implicit def tupleHeadAndTail2[T, A1]: TupleHeadAndTail[(T, A1), T, A1] = null

  implicit def tupleHeadAndTail3[T, A1, A2]: TupleHeadAndTail[(T, A1, A2), T, (A1, A2)] = null

  implicit def tupleHeadAndTail4[T, A1, A2, A3]: TupleHeadAndTail[(T, A1, A2, A3), T, (A1, A2, A3)] = null

  implicit def tupleHeadAndTail5[T, A1, A2, A3, A4]: TupleHeadAndTail[(T, A1, A2, A3, A4), T, (A1, A2, A3, A4)] = null

  implicit def tupleHeadAndTail6[T, A1, A2, A3, A4, A5]: TupleHeadAndTail[(T, A1, A2, A3, A4, A5), T, (A1, A2, A3, A4, A5)] = null

  implicit def tupleHeadAndTail7[T, A1, A2, A3, A4, A5, A6]: TupleHeadAndTail[(T, A1, A2, A3, A4, A5, A6), T, (A1, A2, A3, A4, A5, A6)] =
    null

  implicit def tupleHeadAndTail8[T, A1, A2, A3, A4, A5, A6, A7]
      : TupleHeadAndTail[(T, A1, A2, A3, A4, A5, A6, A7), T, (A1, A2, A3, A4, A5, A6, A7)] = null

  implicit def tupleHeadAndTail9[T, A1, A2, A3, A4, A5, A6, A7, A8]
      : TupleHeadAndTail[(T, A1, A2, A3, A4, A5, A6, A7, A8), T, (A1, A2, A3, A4, A5, A6, A7, A8)] = null

  implicit def tupleHeadAndTail10[T, A1, A2, A3, A4, A5, A6, A7, A8, A9]
      : TupleHeadAndTail[(T, A1, A2, A3, A4, A5, A6, A7, A8, A9), T, (A1, A2, A3, A4, A5, A6, A7, A8, A9)] = null

  implicit def tupleHeadAndTail11[T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10]
      : TupleHeadAndTail[(T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10), T, (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)] = null

  implicit def tupleHeadAndTail12[T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11]
      : TupleHeadAndTail[(T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11), T, (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11)] = null

  implicit def tupleHeadAndTail13[T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12]
      : TupleHeadAndTail[(T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12), T, (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12)] =
    null

  implicit def tupleHeadAndTail14[T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13]: TupleHeadAndTail[
    (T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13),
    T,
    (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13)
  ] = null

  implicit def tupleHeadAndTail15[T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14]: TupleHeadAndTail[
    (T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14),
    T,
    (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14)
  ] = null

  implicit def tupleHeadAndTail16[T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15]: TupleHeadAndTail[
    (T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15),
    T,
    (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15)
  ] = null

  implicit def tupleHeadAndTail17[T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16]: TupleHeadAndTail[
    (T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16),
    T,
    (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16)
  ] = null

  implicit def tupleHeadAndTail18[T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17]: TupleHeadAndTail[
    (T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17),
    T,
    (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17)
  ] = null

  implicit def tupleHeadAndTail19[T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18]: TupleHeadAndTail[
    (T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18),
    T,
    (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18)
  ] = null

  implicit def tupleHeadAndTail20[T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19]
      : TupleHeadAndTail[
        (T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19),
        T,
        (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19)
      ] = null

  implicit def tupleHeadAndTail21[T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20]
      : TupleHeadAndTail[
        (T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20),
        T,
        (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20)
      ] = null

  implicit def tupleHeadAndTail22[T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21]
      : TupleHeadAndTail[
        (T, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21),
        T,
        (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21)
      ] = null

}
