# https://scala-lang.org/blog/2022/07/18/secure-your-dependencies-on-github.html
name: Update Dependency Graph

on:
  push:
    branches:
      - master

permissions:
  contents: write # needed to submit the dependency graph

jobs:
  update-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: sbt/setup-sbt@6bec67c98f542b9e17369bfca0ec822ac1363194 # v1, specifically v1.1.19
      - uses: scalacenter/sbt-dependency-submission@9669cfe68c94145724025cf952bced3cd02ca596 # v3, specifically v3.1.1
