# https://scala-lang.org/blog/2022/07/18/secure-your-dependencies-on-github.html
name: Update Dependency Graph

on:
  push:
    branches:
      - master

permissions:
  contents: write # needed to submit the dependency graph

jobs:
  update-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b # v1, specifically v1.2.1
      - uses: scalacenter/sbt-dependency-submission@d84eef4c09e633bcf5f113bcad7fd5e9af1baee9 # v3, specifically v3.1.1
