# This workflow will launch at 00:00 every day
# It can be also triggered manually using the workflow_dispatch event
on:
# TODO: uncomment after test
#  schedule:
#    - cron: '0 0 * * *'
# TODO: remove after test
  push:
    branches:
      - 2183-add-scala-steward-action

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./github/workflows/ci.yml
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
          key: sbt-cache-${{ runner.os }}-${{ matrix.target-platform }}-${{ hashFiles('project/build.properties') }}
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          author-name: scala-steward
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-config: .scala-steward.conf
          ignore-opts-files: false
# TODO: remove after test
          branches: 2183-add-scala-steward-action
      - name: Cleanup
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "*-LM-SNAPSHOT*"       -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
