# This workflow will launch at 00:00 every day
# It can be also triggered manually using the workflow_dispatch event
on:
# TODO: uncomment
#  schedule:
#    - cron: '0 0 * * *'
#  workflow_dispatch:
# TODO: remove
  push:
    branches:
      - 2183-update-scala-steward-action

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
          key: sbt-cache-${{ runner.os }}-${{ matrix.target-platform }}-${{ hashFiles('project/build.properties') }}
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-config: .scala-steward.conf
          ignore-opts-files: false
# TODO: remove
          branches: 2183-update-scala-steward-action